# ============================================================================
# AUTHENTICATION FAILURE RESPONSE PLAYBOOK
# ============================================================================
#
# Automated response playbook for authentication failures
# Brute force and credential stuffing attack mitigation
#
# Created by: DEVOPS-AGENT - TIER 1 Advanced Threat Protection
# Date: 2025-08-14
# Version: 1.0.0
# ============================================================================

name: "Authentication Failure Response"
description: "Automated response to authentication failures and brute force attacks"
enabled: true
severity_threshold: "medium"

triggers:
  - "authentication_failure"
  - "failed_login"
  - "invalid_credentials"
  - "brute_force"
  - "credential_stuffing"

conditions:
  - type: "threshold"
    metric: "failed_attempts"
    value: 5
    timeframe: "5m"
    
  - type: "rate"
    metric: "attempts_per_minute"
    value: 10
    source: "same_ip"

actions:
  - type: "block_ip"
    params:
      duration: "1h"
      reason: "Multiple authentication failures"
      
  - type: "send_alert"
    params:
      channels: ["slack"]
      priority: "medium"
      message: "Potential brute force attack detected"
      
  - type: "create_ticket"
    params:
      assigned_to: "security-team"
      priority: "medium"
      category: "authentication-security"

escalation:
  - condition: "persistent_attempts"
    threshold: 20
    timeframe: "1h"
    actions:
      - type: "extend_block"
        params:
          duration: "24h"
      - type: "send_alert"
        params:
          priority: "high"
          
  - condition: "multiple_users_targeted"
    threshold: 5
    timeframe: "15m"
    actions:
      - type: "send_alert"
        params:
          priority: "critical"
          message: "Coordinated authentication attack detected"

mitigation:
  - action: "enable_rate_limiting"
    params:
      duration: "2h"
      limit: "3_per_minute"
      
  - action: "require_captcha"
    params:
      duration: "1h"
      
  - action: "force_mfa"
    params:
      affected_users: "all_failed_attempts"

recovery:
  - action: "analyze_patterns"
    params:
      timeframe: "24h"
      include_geolocation: true
      
  - action: "update_blocklist"
    params:
      auto_update: true