/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ops/bins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create bin */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBin"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bin"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateBin: {
            serialNumber: string;
            /** @enum {string} */
            type: "ROLL_OFF" | "FRONT_LOAD" | "REAR_LOAD";
            capacity: number;
            customerId: string;
            latitude: number;
            longitude: number;
        };
        Bin: {
            id: string;
            serialNumber: string;
            type: string;
            capacity: number;
            customerId: string;
            latitude?: number;
            longitude?: number;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE" | "MAINTENANCE";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
