# ============================================================================
# ELASTICSEARCH SIEM CONFIGURATION
# ============================================================================
#
# Production-ready Elasticsearch configuration for SIEM infrastructure
# Optimized for security event storage and real-time analysis
#
# Created by: DEVOPS-AGENT - TIER 1 Advanced Threat Protection
# Date: 2025-08-14
# Version: 1.0.0
# ============================================================================

# Cluster Configuration
cluster.name: waste-mgmt-siem-cluster
node.name: siem-elasticsearch-node-1
node.roles: [ master, data, ingest ]

# Network Configuration
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery Configuration (Single Node for SIEM)
discovery.type: single-node

# Path Configuration
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Memory Configuration
bootstrap.memory_lock: true

# Security Configuration
xpack.security.enabled: true
xpack.security.enrollment.enabled: true

# Authentication Configuration
xpack.security.authc.realms.native.native1:
  order: 0

# SSL/TLS Configuration (Disabled for internal cluster communication)
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Security Features
xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.include: 
  - access_denied
  - access_granted
  - anonymous_access_denied
  - authentication_failed
  - authentication_success
  - change_password
  - connection_denied
  - connection_granted
  - tampered_request
  - run_as_denied
  - run_as_granted

# Index Configuration for SIEM Data
action.auto_create_index: "+siem-*,+security-*,+logs-*,+wazuh-*,+suricata-*,+falco-*,-*"

# Index Templates for Security Data
index.number_of_shards: 1
index.number_of_replicas: 0
index.refresh_interval: 5s

# Performance Optimization for SIEM Workloads
indices.memory.index_buffer_size: 20%
indices.memory.min_index_buffer_size: 96mb

# Thread Pool Configuration for High Throughput
thread_pool.write.size: 4
thread_pool.write.queue_size: 10000
thread_pool.search.size: 6
thread_pool.search.queue_size: 10000

# Circuit Breaker Configuration
indices.breaker.total.limit: 70%
indices.breaker.request.limit: 40%
indices.breaker.fielddata.limit: 40%

# Monitoring Configuration
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

# Machine Learning (Disabled for Resource Conservation)
xpack.ml.enabled: false

# Watcher (Alert Framework)
xpack.watcher.enabled: true

# Graph (Disabled for Resource Conservation)
xpack.graph.enabled: false

# License Type
xpack.license.self_generated.type: basic

# Cross-Cluster Search (Disabled)
cluster.remote.connect: false

# Index Lifecycle Management for SIEM Data
xpack.ilm.enabled: true

# SIEM-Specific Index Settings
index.mapping.total_fields.limit: 2000
index.mapping.depth.limit: 40
index.mapping.nested_fields.limit: 100

# Logging Configuration
logger.org.elasticsearch.discovery: WARN
logger.org.elasticsearch.cluster.service: INFO
logger.org.elasticsearch.indices.recovery: DEBUG
logger.org.elasticsearch.gateway: DEBUG

# Security Event Processing Optimization
indices.query.bool.max_clause_count: 2048

# Real-time Indexing for Security Events
index.translog.durability: async
index.translog.sync_interval: 5s
index.translog.flush_threshold_size: 512mb

# Compression for Long-term Storage
index.codec: best_compression

# Recovery Configuration
cluster.routing.allocation.node_concurrent_recoveries: 2
cluster.routing.allocation.node_initial_primaries_recoveries: 4

# SIEM Index Patterns
# siem-events-*: Real-time security events
# security-alerts-*: Generated security alerts
# logs-application-*: Application logs
# wazuh-alerts-*: Wazuh HIDS alerts
# suricata-*: Network intrusion detection
# falco-*: Runtime security monitoring