openapi: 3.0.3
info: { title: operations-service, version: 0.1.0 }
paths:
  /ops/bins:
    post:
      summary: Create bin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBin'
      responses:
        "201": { description: Created, content: { application/json: { schema: { $ref: '#/components/schemas/Bin' } } } }
components:
  schemas:
    CreateBin:
      type: object
      properties:
        serialNumber: { type: string }
        type: { type: string, enum: [ROLL_OFF, FRONT_LOAD, REAR_LOAD] }
        capacity: { type: integer, minimum: 1 }
        customerId: { type: string }
        latitude: { type: number, minimum: -90, maximum: 90 }
        longitude: { type: number, minimum: -180, maximum: 180 }
      required: [serialNumber, type, capacity, customerId, latitude, longitude]
    Bin:
      type: object
      properties:
        id: { type: string }
        serialNumber: { type: string }
        type: { type: string }
        capacity: { type: integer }
        customerId: { type: string }
        latitude: { type: number }
        longitude: { type: number }
        status: { type: string, enum: [ACTIVE, INACTIVE, MAINTENANCE] }
      required: [id, serialNumber, type, capacity, customerId, status]
