# ============================================================================
# SURICATA NETWORK INTRUSION DETECTION SYSTEM CONFIGURATION
# ============================================================================
#
# Production Suricata IDS configuration for network security monitoring
# Real-time network traffic analysis and threat detection
#
# Created by: DEVOPS-AGENT - TIER 1 Advanced Threat Protection
# Date: 2025-08-14
# Version: 1.0.0
# ============================================================================

# Global Configuration
%YAML 1.1
---

# Suricata Version
suricata: 6.0.0

# Variables
vars:
  # Network Configuration for Waste Management System
  address-groups:
    HOME_NET: "[172.20.0.0/16,172.30.0.0/16,10.0.0.0/8,192.168.0.0/16]"
    EXTERNAL_NET: "!$HOME_NET"
    
    # Application-Specific Networks
    HTTP_SERVERS: "[172.20.0.0/16]"
    SMTP_SERVERS: "$HOME_NET"
    SQL_SERVERS: "[172.20.0.3]"  # PostgreSQL
    DNS_SERVERS: "$HOME_NET"
    
    # DMZ and Management Networks
    DMZ_NET: "[172.30.0.0/16]"
    MANAGEMENT_NET: "$HOME_NET"

  port-groups:
    # Standard Service Ports
    HTTP_PORTS: "80"
    HTTPS_PORTS: "443"
    SHELLCODE_PORTS: "!80"
    ORACLE_PORTS: "1521"
    SSH_PORTS: "22"
    DNP3_PORTS: "20000"
    MODBUS_PORTS: "502"
    FILE_DATA_PORTS: "[$HTTP_PORTS,110,143]"
    FTP_PORTS: "21"
    
    # Application-Specific Ports
    BACKEND_PORTS: "3001"
    FRONTEND_PORTS: "3000"
    POSTGRES_PORTS: "5432"
    REDIS_PORTS: "6379"
    ELASTICSEARCH_PORTS: "9200"
    KIBANA_PORTS: "5601"
    PROMETHEUS_PORTS: "9090"
    GRAFANA_PORTS: "3000"

# Default Rule Path
default-rule-path: /var/lib/suricata/rules

# Rule Files for Security Detection
rule-files:
  - suricata.rules
  - emerging-threats.rules
  - waste-management-custom.rules
  - web-application.rules
  - malware.rules
  - botnet.rules
  - sql-injection.rules
  - xss-attacks.rules
  - authentication.rules

# Classification Configuration
classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config

# Threshold Configuration
threshold-file: /etc/suricata/threshold.config

# Logging Configuration
outputs:
  # Fast Log for Real-time Alerts
  - fast:
      enabled: yes
      filename: fast.log
      append: yes

  # Eve JSON Output for SIEM Integration
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      pcap-file: false
      community-id: true
      community-id-seed: 0
      
      types:
        - alert:
            payload: yes
            payload-buffer-size: 4kb
            payload-printable: yes
            packet: yes
            metadata: yes
            http-body: yes
            http-body-printable: yes
            tagged-packets: yes
            xff:
              enabled: no

        - http:
            extended: yes
            custom: [Accept-Encoding, Accept-Language, Authorization]

        - dns:
            query: yes
            answer: yes

        - tls:
            extended: yes

        - files:
            force-magic: no
            force-hash: [md5]

        - smtp:
            extended: yes

        - ssh

        - stats:
            totals: yes
            threads: no
            deltas: no

        - flow

        - netflow

  # Stats Output
  - stats:
      enabled: yes
      filename: stats.log
      append: yes
      totals: yes
      threads: no

  # Syslog Output for System Integration
  - syslog:
      enabled: yes
      facility: local5
      level: Info

# Network Capture Configuration
af-packet:
  - interface: any
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    mmap-locked: yes
    tpacket-v3: yes
    ring-size: 2048
    block-size: 131072
    block-timeout: 10
    use-emergency-flush: yes

# Detection Engine Configuration
detect-engine:
  - profile: high
  - custom-values:
      toclient-groups: 3
      toserver-groups: 25
  - sgh-mpm-context: auto
  - inspection-recursion-limit: 3000
  - prefilter-engines:
    - mpm

# Threading Configuration
threading:
  set-cpu-affinity: no
  cpu-affinity:
    - management-cpu-set:
        cpu: [ "0" ]
    - receive-cpu-set:
        cpu: [ "0" ]
    - worker-cpu-set:
        cpu: [ "all" ]
  detect-thread-ratio: 1.0

# Performance Configuration
max-pending-packets: 1024
runmode: autofp

# Stream Configuration
stream:
  memcap: 128mb
  checksum-validation: yes
  inline: auto
  drop-invalid: yes
  reassembly:
    memcap: 256mb
    depth: 1mb
    toserver-chunk-size: 2560
    toclient-chunk-size: 2560
    randomize-chunk-size: yes

# Host Table Configuration
host:
  hash-size: 4096
  prealloc: 1000
  memcap: 32mb

# Flow Configuration
flow:
  memcap: 128mb
  hash-size: 65536
  prealloc: 10000
  emergency-recovery: 30

# Flow Timeouts
flow-timeouts:
  default:
    new: 30
    established: 300
    closed: 0
    bypassed: 100
    emergency-new: 10
    emergency-established: 100
    emergency-closed: 0
    emergency-bypassed: 50
  tcp:
    new: 60
    established: 600
    closed: 60
    bypassed: 100
    emergency-new: 5
    emergency-established: 25
    emergency-closed: 10
    emergency-bypassed: 25
  udp:
    new: 30
    established: 300
    bypassed: 100
    emergency-new: 10
    emergency-established: 25
    emergency-bypassed: 25
  icmp:
    new: 30
    established: 300
    bypassed: 100
    emergency-new: 10
    emergency-established: 25
    emergency-bypassed: 25

# Defragmentation Configuration
defrag:
  memcap: 32mb
  hash-size: 65536
  trackers: 65536
  max-frags: 65536
  prealloc: yes
  timeout: 60

# Host OS Policy
host-os-policy:
  windows: [0.0.0.0/0]
  bsd: []
  bsd-right: []
  old-linux: []
  linux: []
  old-solaris: []
  solaris: []
  hpux10: []
  hpux11: []
  irix: []
  macos: []
  vista: []
  windows2k3: []

# Application Layer Protocols
app-layer:
  protocols:
    tls:
      enabled: yes
      detection-ports:
        dp: 443
    http:
      enabled: yes
      libhtp:
        default-config:
          personality: IDS
          request-body-limit: 100kb
          response-body-limit: 100kb
          request-body-minimal-inspect-size: 32kb
          request-body-inspect-window: 4kb
          response-body-minimal-inspect-size: 40kb
          response-body-inspect-window: 16kb
          response-body-decompress-layer-limit: 2
          http-body-inline: auto
          swf-decompression:
            enabled: yes
            type: both
            compress-depth: 0
            decompress-depth: 0
          double-decode-path: no
          double-decode-query: no
    ftp:
      enabled: yes
    ssh:
      enabled: yes
    smtp:
      enabled: yes
      mime:
        decode-mime: yes
        decode-base64: yes
        decode-quoted-printable: yes
        header-value-depth: 2000
        extract-urls: yes
        body-md5: no
    dns:
      tcp:
        enabled: yes
        detection-ports:
          dp: 53
      udp:
        enabled: yes
        detection-ports:
          dp: 53

# Logging Configuration
logging:
  default-log-level: notice
  default-log-format: "[%i] %t - (%f:%l) <%d> (%c) -- "
  outputs:
    - console:
        enabled: yes
    - file:
        enabled: yes
        level: info
        filename: /var/log/suricata/suricata.log
    - syslog:
        enabled: no
        facility: local5
        format: "[%i] <%d> -- "

# Packet Capture
pcap:
  - interface: any

# PCAP Logging (Disabled for Performance)
pcap-log:
  enabled: no

# CPU Profiling (Disabled in Production)
profiling:
  rules:
    enabled: no
    filename: rule_perf.log
    append: yes
  keywords:
    enabled: no
    filename: keyword_perf.log
    append: yes
  prefilter:
    enabled: no
    filename: prefilter_perf.log
    append: yes
  rulegroups:
    enabled: no
    filename: rule_group_perf.log
    append: yes
  packets:
    enabled: no
    filename: packet_stats.log
    append: yes
    csv:
      enabled: no
      filename: packet_stats.csv

# Coredump Configuration
coredump:
  max-dump: unlimited

# SIEM Integration Settings
# - Real-time alerting for security events
# - JSON output for log analysis
# - Custom rules for waste management application security
# - Network traffic monitoring for API endpoints
# - Database connection monitoring
# - Web application attack detection